name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: pip install localstack --verbose
    - name: test
      run:  pip show localstack
    - name: test
      run:  export PATH="$PATH:/home/runner/.local/lib/python2.7/site-packages"
    - name: Run a multi-line script
      run: localstack start --host
